### ISSUE TITLE
Error while importing sonnet about gast

### ISSUE THREAD

**Issue by pshrini** [deepmind/graph_nets#137] opened 2021-02-03 13:07 UTC
----
ConversionError: converting <function BaseBatchNorm.__call__ at 0x00000268C3EF7950>: AttributeError: module 'gast' has no attribute 'Constant'
-----
My gast version is 0.3.3
Tensorflow 2.3.1
graph-nets 1.1
---
How I installed graph-nets
 pip install "graph_nets>=1.1" "tensorflow>=2.1.0-rc1" "dm-sonnet>=2.0.0b0" tensorflow_probability
--
This is on my Windows PC.

**Comment by alvarosg** [comment] 2021-02-08 17:17
(This seems to be a duplicate of #136, so let's continue the discussion there)

Since this seems to be Sonnet related, I would recommend raising an issue against the `sonnet` [repo](https://github.com/deepmind/sonnet/issues), including the full stack trace of the error.

**Closed** 2021-02-08 17:20 UTC
